### ISSUE TITLE
AsyncioExecutor stores every future after executing with no automatic clearing

### ISSUE THREAD

**Issue by slash-oleh** [graphql-python/graphql-core-legacy#104]
I have one AsyncioExecutor instance reusing per each graphql query. I've found my application leaking a lot of memory, especially while fetching a lot of data. After some debugging I've figured out that AsyncioExecutor has a list of futures that it executes. And this list grows up after every query and there is no clear until we destroy executor or clear this list manually. Also I can't find a usage of that list, so I tried to remove appending operation and now everything is fine. So is there a point to store that futures?

This case was tested using [graphene-peewee-async](https://github.com/insolite/graphene-peewee-async). If needed, I can provide a test case.

[graphql/execution/executors/asyncio.py#L49](https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/executors/asyncio.py#L49)

**Comment by slash-oleh** [comment]
Well, `self.futures` is used in `wait_until_finished()` method but in my case it is not even called (which is good, cause is it not async actually). And yet, there is no list clear. Probably it should be after `wait` or should be more obvious if clearing is intended to be up to user?

**Comment by syrusakbary** [comment]
This issue is now resolved in latest versions :)

**Comment by joar** [comment]
I'm guessing it's fixed in 2.1, is that correct?

**Comment by syrusakbary** [comment]
That's correct
