### ISSUE TITLE
is_leaf_type() returns True when the type is List of String

### ISSUE THREAD

**Issue by obi1kenobi** [graphql-python/graphql-core-legacy#105]
```
In [1]: from graphql import GraphQLString, GraphQLList

In [2]: from graphql.type.definition import is_leaf_type

In [3]: is_leaf_type(GraphQLList(GraphQLString))
Out[3]: True
```

See the current `master` implementation [here](https://github.com/graphql-python/graphql-core/blob/cfeaa393259266572e634f6e7e8dfd4fc591b2a4/graphql/type/definition.py#L43): `is_leaf_type()` calls `get_named_type()`, which unwinds both lists and non-nulls to get at the inner type. The list unwinding is incorrect in this instance, as a list of strings is clearly a non-leaf type.

This is all using `graphql-core` version `1.0.1`, the newest available on PyPI.

**Comment by syrusakbary** [comment]
Good catch. This was fixed in GraphQL-js in this commit: https://github.com/graphql/graphql-js/commit/12b2137f8a0b1a72752b5ee54660127a5a042a33

A PR reflecting those changes will be always welcome! :)

**Comment by obi1kenobi** [comment]
@syrusakbary thanks for finding the JS version fix. I made a quick PR with the change you proposed.

On a validation-related note, do you think #97 might be something that's fixed in the upstream JS project, or could it be a new bug? I wasn't able to find it in the list of issues in that project, but perhaps you are more familiar with it and are better equipped to find the answer.
