### ISSUE TITLE
How do you correctly get exceptions?

### ISSUE THREAD

**Issue by janhancic** [graphql-python/graphql-core-legacy#113]
So I want to log out the original exception that occurred during the execution of the query and return the exception message to the client in the errors obj. The latter works fine, but I can't, for the life of me, get the stack of the exception.

I have the execution result and I tried things like this:

```
if execution_result.errors:
  [logger.exception(e) for e in execution_result.errors]
  # or 
  [logger.exception(e.original_error) for e in execution_result.errors]
  # or
  [logger.info(e) for e in execution_result.errors]
  # or 
  [logger.info(e.original_error) for e in execution_result.errors]
```

But it only prints out the message of the exception, which isn't very useful when debugging.

I'm on 1.0. of graphql-core.

Also when will there be a new release? I'm currently patching some bugs that have been fixed in master but haven't been released yet and I'd rather not do that :)

Thanks!

**Comment by janhancic** [comment]
Hey @syrusakbary I've done some more digging around and I found that the exceptions get caught here: https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/executor.py#L212

at which point they are already missing their stack trace. I tried digging deeper from there, going into the promise lib but I couldn't find anything.

Can you point me in the right direction? I'm happy to provide a PR but am a bit lost at the moment as to where to start looking further.

**Comment by janhancic** [comment]
Is there any more information I can provide to make this easier to solve?

Also, cheers for the new release! I'll be upgrading soon.

**Comment by janhancic** [comment]
I've just upgraded to `promise v2`, `graphql-core v1.1` and `graphene v1.4` and the behaviour is the same. Just FYI.

**Comment by kvey** [comment]
```
    mutation = schema.execute(query, variable_values={
        "foo": "bar")
    })
    if mutation.errors:
        traceback.print_tb(mutation.errors[0].stack, limit=10, file=sys.stdout)
```

is a snippet I've been using in tests if it's helpful

**Comment by janhancic** [comment]
Seems like this is no longer an issue on latest versions (not sure why it didn't work when I wrote my previous comment). Will close this and re-open if I find any similar issues.

Thanks.
