### ISSUE TITLE
Bringing graphl-core in line with graphql-js

### ISSUE THREAD

**Issue by audiolion** [graphql-python/graphql-core-legacy#145]
Hello!

Wondering what the state is for this repo, its mirroring up until `0.6.0` of the `graphql-js` library, are there plans to bring this up to the most recent version?

There seems to be a few changes to the `ast` syntax in that time

https://github.com/graphql/graphql-js/compare/3f1f9f5759704ca9ed153c98558236a66af75153...master#diff-f6c82657a3a445e0f3fcc8409482756c

go to "files changed" tab and search for `ast.js` to see the diff

If you want help I would love to get involved to aid in this endeavor!

**Comment by KaySackey** [comment]
The link you gave, doesn't show any changes between those two branches. Was that the right link?

**Comment by audiolion** [comment]
Ok updated the link, thanks!

**Comment by Cito** [comment]
Version 3 of graphql-core is pretty much up to date with the current graphql-js now.

Version 2 of graphql-core will not get larger updates in order to stay backward compatible.
