### ISSUE TITLE
Updates to RxPY (vNext)

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphql-core-legacy#152]
As a heads up, I was talking with the maintainer of RxPY and there will be major changes to the library by year's end. This major change will be both a refactor of RxPY and will also support the notion of an `AsyncObservable`, bridged from the `aioreactive` library: [RxPy vNext](https://github.com/ReactiveX/RxPY/tree/vnext).

I think the major benefit to `graphql-core` will be that we could remove the [`AsyncgenObservable`](https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/executors/asyncio_utils.py#L55) as this should be natively supported (from [`aioreactive`](https://github.com/dbrattli/aioreactive#asynchronous-iteration)).

**Comment by syrusakbary** [comment]
This is great news!

**Comment by syrusakbary** [comment]
I've checked and I'm not sure if this changes are currently on the stable version of RxPy or not.
Do you know if that's the case @dfee ?

**Comment by dfee** [comment]
Unfortunately, I don't think it's been merged yet.

**Comment by syrusakbary** [comment]
Thanks to @ciscorn awesome work on #184, `AsyncgenObservable` is no longer needed.

Closing the issue, but feel free to re-open it once RxPy vNext is released :)
