### ISSUE TITLE
ResolveInfo.field_name is camelCased

### ISSUE THREAD

**Issue by janhancic** [graphql-python/graphql-core-legacy#162]
`field_name` on the `ResolveInfo` is in camelCase, so you need to convert it to snake_case to make it usable in Python.

Would it make sense to convert it? I guess same goes for the requested fields in field_asts.

**Comment by jkimbo** [comment]
@janhancic I don't think it does make sense since this library is meant to be a port of the `graphql-js` reference implementation. The automatic conversion from snake case to camel case is a developer nicety that is implemented in graphene only.

**Comment by janhancic** [comment]
Do you think that's something that could be implemented in graphene then? At the moment I'm doing the conversion manually as otherwise it's weird that in some cases you use camel case and in some snake case.

**Comment by jkimbo** [comment]
Sure it seems reasonable. Happy to have a look at a PR with tests on the graphene repo

**Comment by janhancic** [comment]
Seems like something that could go hand in hand with #160 in that it could be a new field on the info object. Otherwise it would be a bit of a backwards compatibility issue, as there's code out there expecting snakeCase.

I might have some time in the near-ish future to do this, but would need some buy in from the maintainers first.

**Comment by jkimbo** [comment]
Yep agreed there would be a couple of issues solved with something like a `selection_fields` attribute on the info object (name is completely up for grabs). Probably only useful on an `ObjectType` resolver though. Again happy to look at a PR on the graphene repo (where I am a maintainer) since that code should live there.

**Comment by janhancic** [comment]
Oh, sorry, didn't realise you're a maintainer there ☺️
I'm not promising anything, but will see what I can do.
