### ISSUE TITLE
ImportError: cannot import name GraphQLEnumValue

### ISSUE THREAD

**Issue by cmacrander** [graphql-python/graphql-core-legacy#167]
To reproduce:

1. With python 2.7, create a new virtual environment.
2. `pip install graphql-core`
3. Create a file, `main.py` with the line `from graphql import GraphQLEnumValue`
4. Run the file, see error `ImportError: cannot import name GraphQLEnumValue`

I was attempting this because comments in the library show examples like this one. Note the references to `GraphQLEnumValue`.

```
class GraphQLEnumType(GraphQLType):
    """Enum Type Definition

    Some leaf values of requests and input values are Enums. GraphQL serializes Enum values as strings,
    however internally Enums can be represented by any kind of type, often integers.

    Example:

        RGBType = GraphQLEnumType(
            name='RGB',
            values=OrderedDict([
                ('RED', GraphQLEnumValue(0)),
                ('GREEN', GraphQLEnumValue(1)),
                ('BLUE', GraphQLEnumValue(2))
            ])
        )
```

**Comment by jkimbo** [comment]
@cmacrander looks like it's not exposed at the top level of the package. You can import it like this: `from graphql.type import GraphQLEnumValue`

**Comment by chris-perts** [comment]
Thanks, @jkimbo, I'll do that. Still, I noticed that everything else (e.g. `GraphQLEnumType`) is exposed in that manner. And my naïve reading of `__init__.py` suggests it _should_ be exposed. The fact that it's not suggests a more subtle bug. What do you think?

**Comment by jkimbo** [comment]
I think it's just an oversight. This library is a port of the JS library and there isn't such as thing as `GraphQLEnumValue` there. If you would like to make a PR to expose it at the top level I'm sure that would be appreciated.
