### ISSUE TITLE
Release 2.0.1?

### ISSUE THREAD

**Issue by bryanhelmig** [graphql-python/graphql-core-legacy#170]
It's been a little quiet around here, but I did notice in 2018 we have a merge of both:

* https://github.com/graphql-python/graphql-core/pull/148
* https://github.com/graphql-python/graphql-core/pull/154

And looks like the version is set to 2.0.1 in trunk -- can we get it release to pypi?

We released an internal fork of this library internally to get the goodies in master in our codebase.

**Comment by andrroy** [comment]
+1, it would be super useful for us to have the current code released to a new version. Right now, we have the same problem as @bryanhelmig, where we have to fork on order to get the latest code

**Comment by dan98765** [comment]
+1 would be useful, in particular to get the feature of having 'path' in the error output in a version on pypi.

**Comment by syrusakbary** [comment]
New versions are being released, with tons of improvements.
Feel free to use them by doing `pip install "graphql-core>=2.1rc3"`
