### ISSUE TITLE
Invalid python 2.7 syntax in MiddlewareManager

### ISSUE THREAD

**Issue by dan98765** [graphql-python/graphql-core-legacy#189]
https://github.com/graphql-python/graphql-core/blob/24be647e0cf12b0a12d858c4791f34a9bd210be3/graphql/execution/middleware.py#L13

Sadly having *args before a kwarg is only allowed in py3+.

https://stackoverflow.com/questions/22435992/python-trying-to-place-keyword-arguments-after-args

https://stackoverflow.com/questions/38595509/python-2-7-functions-with-positional-keyword-arguments-as-well-as-variable-num

**Comment by syrusakbary** [comment]
Just fixed this in: https://github.com/graphql-python/graphql-core/commit/b24cece36c00975f39751b2cff7538604c329520

Thanks for the ping!
