### ISSUE TITLE
Option for strict key ordering in results.

### ISSUE THREAD

**Issue by jhgg** [graphql-python/graphql-core-legacy#19]
Related to #18, sometimes users might want their results to be in the same order as they are in the fields. In this case, I am thinking that it should be an optional argument (default False) to the `Executor`.

In the default, it will use regular `dict` objects to store results. But if say `enforce_strict_ordering=True` is passed to the Executor, then we will use `OrderedDict` instead.

**Comment by syrusakbary** [comment]
What about instead of `enforce_strict_ordering` arg, one that says `map_type=dict` and we can init the executor if we want strict ordering with `map_type=OrderedDict`?
Maybe the last one (`map_type`) will be more flexible... thoughts?

**Comment by jhgg** [comment]
I was thinking that is going to be the way to go.

**Comment by jhgg** [comment]
But the only issue is that there are some places where we need to signify that strict ordering is needed. For example, `collect_fields` will need to take OrderedDict instead of Dict, but that collected value is never returned as a result. Thus my concern with exposing the direct `map_type` to the API.

**Comment by jhgg** [comment]
I can always check to see if map_type is an instance of `OrderedDict`.

**Comment by syrusakbary** [comment]
You mean in here https://github.com/graphql-python/graphql-core/blob/master/graphql/core/execution/executor.py#L85 right?

Maybe creating a wrapper around the map for allowing to have default values?
Or it might be not worth the effort... you decide! :wink:

**Comment by syrusakbary** [comment]
Awesome work! :+1: @jhgg
