### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by miracle2k** [graphql-python/graphql-core-legacy#21]
I scalars.py, this line:

```
def coerce_string(value):
    if isinstance(value, bool):
        return 'true' if value else 'false'
    return unicode(value)
```

If the input value of a mutation is a unicode string, I get a decode error. A simple fix, `unicode(value)` handles this for me.

**Comment by jhgg** [comment]
Hey. Can you provide code to repro the case where this happens, so we can put it in as a unittest?

Thanks!

**Comment by syrusakbary** [comment]
I think the "If the input value of a mutation is a unicode string" is the test case ;)

**Comment by jhgg** [comment]
It shouldn't though. Which is why I'm wondering what's causing the error.
