### ISSUE TITLE
Allow constant names with dash

### ISSUE THREAD

**Issue by gildub** [graphql-python/graphql-core-legacy#218]
Would it be possible to flex the following assert_valid_name check and allow dash?
https://github.com/graphql-python/graphql-core/blob/master/graphql/utils/assert_valid_name.py#L3

For example using the following:
```python
NAME_PATTERN = r"^[_a-zA-Z][_\-a-zA-Z0-9]*$"
```

The reason behind is it's breaking https://review.openstack.org/#/c/575898/16.

**Comment by gildub** [comment]
The typical error would be:
```python
.../...
File "/home/gildub/github/openstack/neutron/.tox/py27/lib/python2.7/site-packages/graphql/utils/assert_valid_name.py", line 12, in assert_valid_name
    ), 'Names must match /{}/ but "{}" does not.'.format(NAME_PATTERN, name)
AssertionError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "dhcpv6-stateful" does not.
```

**Comment by Cito** [comment]
That would be against the GraphQL spec https://spec.graphql.org/June2018/#sec-Names
