### ISSUE TITLE
Implement outstanding tests

### ISSUE THREAD

**Issue by jhgg** [graphql-python/graphql-core-legacy#23]
This issue is just a check-list of outstanding tests I need to implement.

If you plan to help, please comment before starting work on any of these tests so we don't do the same work at the same time. If there's a name by the checkbox, that person is working on implementing those tests.
## Type Tests
- [X] @jhgg https://github.com/graphql/graphql-js/blob/master/src/type/__tests__/definition.js 
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/type/__tests__/enumType.js 
- [X] @jhgg https://github.com/graphql/graphql-js/blob/master/src/type/__tests__/introspection.js
- [X] @jhgg https://github.com/graphql/graphql-js/blob/master/src/type/__tests__/serialization.js
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/type/__tests__/validation.js #8 
## Executor Tests
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/abstract.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/directives.js
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/executor.js (may be split between test_executor and test_concurrent_executor -- reconcile tests)
- [X] https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/executor_schema.js  
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/lists.js 
- [X] https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/mutations.js
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/nonnull.js
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/union-interface.js
- [x] @jhgg https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/variables.js
## Language Tests
- [X]  https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/lexer.js https://github.com/graphql-python/graphql-core/commit/6c52d0f083baccb6d450c1893e20c0acf6dce52b
- [X] https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/parser.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/printer.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-parser.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-printer.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/visitor.js
## Utility Tests
- [X] https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/astFromValue.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/buildASTSchema.js
- [x] https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/buildClientSchema.js #5
- [X] https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/getOperationAST.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/schemaPrinter.js
## Validation Tests
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/ArgumentsOfCorrectType.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/DefaultValuesOfCorrectType.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/FieldsOnCorrectType.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/FragmentsOnCompositeTypes.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/KnownArgumentNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/KnownDirectives.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/KnownFragmentNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/KnownTypeNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/LoneAnonymousOperation.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/NoFragmentCycles.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/NoUndefinedVariables.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/NoUnusedFragments.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/NoUnusedVariables.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/OverlappingFieldsCanBeMerged.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/PossibleFragmentSpreads.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/ProvidedNonNullArguments.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/ScalarLeafs.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/UniqueArgumentNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/UniqueFragmentNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/UniqueInputFieldNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/UniqueOperationNames.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/VariablesAreInputTypes.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/VariablesInAllowedPosition.js
- [X] https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__/harness.js
## Starwars
- [X] https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsQueryTests.js
- [X] https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsValidationTests.js

**Comment by rawls238** [comment]
wow this is great work @jhgg. Is there anything else we need to do to reach feature-parity with graphql-js?

**Comment by jhgg** [comment]
Nope. I just am working on finishing up the remaining executor tests. And we are good. It's done. Now to test and see where I messed up.

**Comment by jhgg** [comment]
@rawls238 you can read the release notes here for the current status: https://github.com/graphql-python/graphql-core/releases/tag/v0.4.7b0

**Comment by jhgg** [comment]
I could use some help with documenting things tho.
