### ISSUE TITLE
RX dependancy conflict for Python 2.7

### ISSUE THREAD

**Issue by Nabellaleen** [graphql-python/graphql-core-legacy#235]
It seems RX > 3.0 is not anymore compatible with python 2.7, so I get this error on graphene-sqlalchemy build, as mentionned in https://github.com/graphql-python/graphene-sqlalchemy/pull/177#issuecomment-477218178

I prepare a PR to fix it

**Comment by jeremytubbs** [comment]
+1

**Comment by Cito** [comment]
Fixed in version 2.2.1.
