### ISSUE TITLE
Add Decimal Type

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphql-core-legacy#24]
We have `GraphQLFloat` and `GraphQLInt`, as Python also have the native implementation of a `Decimal`, would be great if we can add the type `GraphQLDecimal`.

**Comment by jhgg** [comment]
This should not be built into graphql-core, as it's not defined in the GraphQL standard.
If you want to use Decimals, I'd recommend implementing your own Decimal Scalar Type:

``` python
def coerce_decimal(value):
    try:
        return Decimal(value)
    except ValueError:
        pass

def parse_decimal_literal(value_ast):
    if isinstance(value_ast, (ast.StringValue, ast.IntValue, ast.FloatValue)):
        return Decimal(value_ast.value)

DecimalType = GraphQLScalar(name='Decimal', serialize=str, parse_value=coerce_decimal, parse_literal=parse_decimal_literal)
```
