### ISSUE TITLE
Possible logic issue with unreachable code

### ISSUE THREAD

**Issue by ambientlight** [graphql-python/graphql-core-legacy#242]
Was looking into subscriptions and found this:

https://github.com/graphql-python/graphql-core/blob/9333075c657e91e563c09add8464f3758e317749/graphql/execution/executor.py#L306-L312

The desired intention here is merging field subscriptions into single observable?

**Comment by ekampf** [comment]
It does like like `return observable` shouldn't be there.

**Comment by Cito** [comment]
The reason for this is probably that the whole code is only tested and functional when there is only one field anyway. I have now made the code more clear in this regard.

Closing this here. If anybody wants to solve this properly, this is still open as #194.
