### ISSUE TITLE
Plans for a release >2.3.1

### ISSUE THREAD

**Issue by blazewicz** [graphql-python/graphql-core-legacy#279]
Are there any plans for a new release?

Some annoying typing issues where fixed since last release https://github.com/graphql-python/graphql-core-legacy/compare/v2.3.1...master 4 months ago. For example, following error I'm getting with mypy==0.770 is already [fixed](https://github.com/graphql-python/graphql-core-legacy/commit/f3425236d2c193037486b83674e9fdb3bf6aaf57), but awaits a release:

```
***: error: Argument "loop" to "AsyncioExecutor" has incompatible type "AbstractEventLoop"; expected "Optional[_UnixSelectorEventLoop]"
```

**Comment by Cito** [comment]
Version 2.3.2 with these fixes has been released now.
