### ISSUE TITLE
GraphQLArgument with default_value None

### ISSUE THREAD

**Issue by faassen** [graphql-python/graphql-core-legacy#28]
In wsgi_graphql at https://github.com/faassen/wsgi_graphql I have tests in the test suite when I update to graphql-core. These are caused by the handling of default_value. If you omit `default_value` (which I do in test_wsgi_graphql.TestSchema) it is set to `None`. This now causes error messages in `graphql-core`, which
weren't there in `graphqllib` before, and it doesn't seem to be right in general: the `express-graphql` tests also omit the default value and this works fine.

You can make the tests pass by putting in a `default_value` of `False` explicitly:

```
                args={
                    'who': GraphQLArgument(
                        type=GraphQLString,
                        default_value=False
                    )
                },
```

**Comment by jhgg** [comment]
What error message?

**Comment by faassen** [comment]
So I get things back like this:

```
{u'errors': [{u'message': u"'who'", u'locations': [{u'column': 2, u'line': 1}]}], u'data': {u'test': None}}
```

Instead of the expected:

```
{u'data': {u'test': u'Hello World'}}
```

**Comment by jhgg** [comment]
Can you paste the full code?

**Comment by faassen** [comment]
```
def raises(*_):
    raise Exception("Throws!")


def resolver(root, args, *_):
    return 'Hello ' + (args['who'] or 'World')


TestSchema = GraphQLSchema(
    query=GraphQLObjectType(
        'Root',
        fields=lambda: {
            'test': GraphQLField(
                GraphQLString,
                args={
                    'who': GraphQLArgument(
                        type=GraphQLString,
                        default_value=False
                    )
                },
                resolver=resolver
            ),
            'thrower': GraphQLField(
                GraphQLNonNull(GraphQLString),
                resolver=raises
            )
        }
    )
)
```

is the schema involved.

**Comment by faassen** [comment]
The query is for `{test}`.

**Comment by faassen** [comment]
Oops, `default_value` is missing in the schema, I posted the wrong test schema.

**Comment by jhgg** [comment]
This behavior is working as intended. When `default_value` is set to `None` or omitted (which sets it to `None`), the value should not appear in the `args` dict. 

https://github.com/graphql-python/graphql-core/commit/55dcd92d079a2a6ed886f1c3e9e7b7d68b0b0e3b
https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/executor.js#L626

If you're expecting a defaultValue of `None` use `args.get(key)` instead.

**Comment by syrusakbary** [comment]
@jhgg I think we should be able to have a default value to None, which is different than `undefined`.
The only thing we have to do in the `graphql-core` repo is:

``` python
if key in args:
    return args[key]
raise KeyError(key)
```

wherever this is implemented
EDIT: Probably here https://github.com/graphql-python/graphql-core/blob/master/graphql/core/execution/values.py#L36 ?

**Comment by jhgg** [comment]
`undefined` can never be a default value, even in `graphql-js`. https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L421

**Comment by syrusakbary** [comment]
I'm not saying set to undefined, which is impossible in Python (unless we create the undefined type :P)
I'm saying instead of doing `args.get(blablabla)` we should do the logic I posted before ;)
