### ISSUE TITLE
Implement `extendSchema()` utility.

### ISSUE THREAD

**Issue by jhgg** [graphql-python/graphql-core-legacy#40]
https://github.com/graphql/graphql-js/commit/9ea8196c2af97551bab5cfd57201c29e3085ee4e

**Comment by Globegitter** [comment]
Any update that on this? Error-handling and schema extension are probably right now the two most important features for us. I have also seen that graphene now has an `extend_fields` function which seems to achieve something similar.

See https://github.com/graphql-python/graphene/issues/66

**Comment by jhgg** [comment]
@Globegitter - will probably be over the winter vacation time. I'm very busy at my new job ;(

**Comment by Globegitter** [comment]
That is totally fair - thanks for the response :)

**Comment by syrusakbary** [comment]
@Globegitter you can install the latest `graphql-core` version `0.4.13`, and do the following:

``` python
from graphql.core.utils.extend_schema import extend_schema

new_schema = extend_schema(schema, ast)
```

Hope it helps!
