### ISSUE TITLE
Error message when you return a non-iterable for a `List` in a `resolve_` function should mention the name of the resolve function

### ISSUE THREAD

**Issue by dgoldstein0** [graphql-python/graphql-core-legacy#45]
Particularly this code:

https://github.com/graphql-python/graphql-core/blob/450620de817480e5f36b64b7eb055a2be12abea0/graphql/core/execution/executor.py#L250

Since graphql-core doesn't bubble up exceptions for most problems with the schema - here included - it's entirely nonobvious what types are involved and more importantly, what `resolve_*` function is the cause of this error.  It makes it really hard to debug - turning a 5 minute problem into a "hack your own debugging code in" ~30 minute problem... if you have the mind to try that.  Resolving a bug like this shouldn't take that kind of surgery to debug.

**Comment by jhgg** [comment]
I think this is fixed in master. Just unreleased.  :(

**Comment by dgoldstein0** [comment]
:/ Please release then.  I had a lot of really awful debugging experiences
this week, and I'm trying to evaluate whether this library is fit for
prod... Currently I have to say no.

**Comment by jhgg** [comment]
A few other things need to be done for the 0.4.13 release. Once I have some actual free time I'll get them done. But until then PRs are welcome.

**Comment by dgoldstein0** [comment]
Cool.  What's the expected timeline?

I can't say I'm going to turn around and start submitting pull requests, but I think I can argue that it's not a ton of work for us to fix the shortcomings I've ran into this week.  If we really want to use this library, we'll probably start sending PRs your way.

**Comment by syrusakbary** [comment]
@dgoldstein0 this is now pushed and published. Currently, the latest available graphql-core version is `0.4.18`.
Closing the issue.
