### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphql-core-legacy#46]
Having big mutations and queries it would be really useful having a new version of the library that includes https://github.com/graphql-python/graphql-core/commit/cf10db643abe8a4faf0e5b59c97ec19eefad094b

I actually spent some time implementing it myself just to now realise it has already been implemented without a release. So yeah, that would be a quite nice free win to have :) Thanks!

**Comment by jhgg** [comment]
I'll release a new patch version with it today think it will be 0.4.12.1

**Comment by jhgg** [comment]
Done.

**Comment by Globegitter** [comment]
Thanks!
