### ISSUE TITLE
Path to 0.5.0

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphql-core-legacy#53]
Version `0.5.0` compatible with the `GraphQL` Apr 2016 spec.
_Related Pull Requests:_ #54 #59 
## Features
- [x] Improve error handling #41 
- [x] Add ability to add custom errors (inheriting from `GraphQLError`)
- [x] Expose all the function and classes
- [x] Move modules from `graphql.core.*` to `graphql.*`
- [x] Make tests relative to the directories
- [x] ~~Isolate `promise` package into own package in PyPI~~ `pypromise` ☺️
## Breaking changes

Improve the executor to be closer to the reference implementation:
- [x] Uses `Promise` instead of `Deferred` as it simplifies the implementation. Use parallel resolvers automatically as default behavior when available. Related PR: #59 
## Commit Checklist

Implement the [commits from GraphQL-js](https://github.com/graphql/graphql-js/commits/master?page=3):
- [x] Allow edit nodes on enter and on leave: https://github.com/graphql/graphql-js/commit/ecfdb3bb3e90755a7bff6155af50591d52e75625 + https://github.com/graphql/graphql-js/commit/d2c005afc87353eceadc03592e74bd6e44063e8e
- [x] Nit: fix missing quote in error message: https://github.com/graphql/graphql-js/commit/db0924a91f0a6c4cea8ff9a93713cbfe69c5ae8f
- [x] Add test for parseLiteral on ComplexScalar: https://github.com/graphql/graphql-js/commit/b3a512787618cfbed20c9717daf2d69444bf7f33
- [x] Extract completeListValue function from CompleteValue: https://github.com/graphql/graphql-js/compare/57d71e108afc0bdd205f5019fb8d0143b24b55b6...7a15a3f17452fadf2cc7d4f43fd41a7c24b38c8a + https://github.com/graphql/graphql-js/commit/533fc43f7d5836fc9b6a3eafde9801db9a3ee011
- [x] [RFC] Proposed change to directive location introspection: https://github.com/graphql/graphql-js/commit/e89c19d2ce584f924c2e0e472a61bb805ce260d4
- [x] Fix error message for missing operation + tests: https://github.com/graphql/graphql-js/commit/debf3d1fbffc6b31e3b8425a28d3478d8cc0be78 https://github.com/graphql/graphql-js/commit/3278e861837cd3f7d17eaec54f3f04b175300826
- [x] [RFC] Directives in schema language: https://github.com/graphql/graphql-js/commit/fdafe32724f2d6dac1ba360f1a440c0e633e75d9
- [x] Updating schema parser to more closely match current state of RFC: https://github.com/graphql/graphql-js/pull/323/commits/b0885a038ec0e654962d69fb910ac86659279579
- [x] [RFC] Add Schema Definition to IDL https://github.com/graphql/graphql-js/commit/8379e71f7011fe044574f4bdef2a761d18d6cf2c
- [x] Remove unused function parameters https://github.com/graphql/graphql-js/commit/43992e3a60d7bf8f5e7d2f29dfae302b5ba72eec
- [x] Include test for extending a schema that uses Enums https://github.com/graphql/graphql-js/commit/37924d240d7e094382927e4f612d61ff7dda3cb3
- [x] Cache client schema exe function, and include test for unreferenced interface https://github.com/graphql/graphql-js/commit/1083c7e0f3dbd6be801a12f688fe0959716c54ac
- [x] Naming similarity https://github.com/graphql/graphql-js/commit/3f6a7f4ca9cd9242819e0e14fc7916635fbeeced
- [x] Move getTypeOf to execute.js and rename to defaultResolveTypeFn to mirror defaultResolveFn https://github.com/graphql/graphql-js/commit/edc405a11508a110759ce53c9efb2eb6dd2d181c + https://github.com/graphql/graphql-js/commit/a781b556eea66bbf3cd82e438f560be9d9bec22c
- [x] Add tests and refine default resolve function. https://github.com/graphql/graphql-js/commit/d506c23e413a0b2d5b6b169caca4af928996d1d9
- [x] Add GraphQLSchema types field https://github.com/graphql/graphql-js/commit/6a1f23e1f9c1e6bf4cea837bc9bb6eae0fb5c382 + Fix test https://github.com/graphql/graphql-js/commit/09be751e995dd641f138f67ff9f420525950fad1
- [x] [RFC] Add explicit context arg to graphql execution https://github.com/graphql/graphql-js/commit/d7cc6f9aed462588291bc821238650c98ad53580
- [x] Improve coercion error messages https://github.com/graphql/graphql-js/commit/dea5aacca01f4429026bea3d97ea7cbc88b33bcf + Minor touch ups: https://github.com/graphql/graphql-js/commit/136630f8fd8778c4d2e61d07c0b1ec47f99c9bf6
- [x] Clean up tests https://github.com/graphql/graphql-js/commit/8514211b674d1f282fdff73e412c289435ab6920
- [x] Fix bug where @include directive is ignored if @skip is present. https://github.com/graphql/graphql-js/commit/d6da0bff7f877e6a4fb66119796809f9c207f841 + Spec compliant @skip/@include https://github.com/graphql/graphql-js/commit/47f87fa701cb33fc1fb0ca65b4668c7a14a5ad11
- [x] Fix tests on abstract type invariant https://github.com/graphql/graphql-js/commit/cf5b2340f934c94b6c960d765d9fc26a02fb6250
- [x] Remove non spec compliant test https://github.com/graphql/graphql-js/commit/07e627adda2b236e720ec352b21eb3043170c60f
- [x] Add tests for type comparators https://github.com/graphql/graphql-js/commit/3201ebb825f7bab4ca4856238ade4603e15a5abc
- [x] Add sanity checks for schema to allow only a single query, mutation, subscription in schema https://github.com/graphql/graphql-js/commit/ffe76c51c44922e2a24494ef0def9e3b999caacb
- [x] RFC: Return type overlap validation https://github.com/graphql/graphql-js/commit/c034de91acce10d5c06d03bd332c6ebd45e2213c

**Comment by Globegitter** [comment]
@syrusakbary We have been looking a lot into a parallel middleware in our app (on Python 2.7). I was planning on open sourcing them, but the one we currently use is a simple ThreadPool middleware (the gevent middleware turned out not to be compatible with our app because we use grpc). That has its own issues though because it actually is spinning off threads. So our latest approach would be to use Futures (grpc is also using futures), which has a nice backport to python 2.7: https://github.com/agronholm/pythonfutures as well with an additional package to make it then-able: https://github.com/dvdotsenko/python-future-then

Apart from the fact that this would be neater for our app (so I will already be slightly more biased towards a futures solution), I also do think it is the more pythonic solution and more and more projects (like grpc) do actually implement the futures interface. So this would in my opinion, generally make it easier to integrate with the parallel middleware.

Since this is something that we need in our app and it has been on our internal TODO, that might be something that I, or possibly one of my colleagues could tackle. But the earliest for me would be sometime towards end of next week.

cc @alamaison

**Comment by sdcooke** [comment]
I've ported a few more commits:

Add to unit tests to ensure test accepts both edits of enter and leave: https://github.com/graphql/graphql-js/commit/d2c005afc87353eceadc03592e74bd6e44063e8e
in https://github.com/graphql-python/graphql-core/pull/56

Add test for parseLiteral on ComplexScalar: https://github.com/graphql/graphql-js/commit/b3a512787618cfbed20c9717daf2d69444bf7f33
in https://github.com/graphql-python/graphql-core/pull/57

Extract completeListValue funciton from CompleteValue: https://github.com/graphql/graphql-js/commit/ab774705cf57fd21faf58ce33c360c21d13fe607
Extract completeLeafValue from CompleteValue: https://github.com/graphql/graphql-js/commit/4c5904c69e61fe2bc62cbbbe007016c2d82e24f2
Extract completeObjectValue from CompleteValue: https://github.com/graphql/graphql-js/commit/5a136489f59c934dd9183caac8607c3415a7be07
Extract completeAbstractValue from CompleteValue: https://github.com/graphql/graphql-js/commit/d484f3186a7d9933257a73a7f1240e9abe68895d
Add invariant for unreachable condition: https://github.com/graphql/graphql-js/commit/7a15a3f17452fadf2cc7d4f43fd41a7c24b38c8a
in https://github.com/graphql-python/graphql-core/pull/58

Nit: fix missing quote in error message: https://github.com/graphql/graphql-js/commit/db0924a91f0a6c4cea8ff9a93713cbfe69c5ae8f
is already fixed so doesn't need doing

**Comment by syrusakbary** [comment]
@Globegitter I think using futures is reasonable given the python context.
The main goal for using `Promise`s is simplify the executor classes for only have one that could work in any case (sync or async resolver resolution).

If we could achieve it in a simple way with futures I think would be a good idea to use it instead of `Promise`s. (Seems could be completely possible by using `python-future-then` 😉 )

**Comment by syrusakbary** [comment]
@sdcooke you did a great work!

**Comment by syrusakbary** [comment]
@Globegitter after researching and trying to implement using only futures I realized that everything would work great if we "promesify" the `Future`s automatically and have the advantages of using `Promise`s at the same time.

So we can have the nice approach of `Promise`s, but allowing the developer to use either a `Deferred` or `Future` if they want to. The `Promise` approach will not force any way for choosing how will be the executor (if `asyncio`, `concurrent.futures`, a `Thread` pool and so on), but will be only a layer on top of that.

**Comment by Globegitter** [comment]
@syrusakbary That sounds like a quite good option. What exactly would 'promesifying' `Futures` in your opinion mean? Would this just be adding the `.then` interface or more than that? I suppose a `.catch` could be quite handy as well.

**Comment by syrusakbary** [comment]
@Globegitter What I meant with promesifying `Futures` is wrapping each future in a Promise (will be done in the grapqhl library, with no extra effort from the developer).

Here is the related PR for Promises, if you want a take al look.
https://github.com/graphql-python/graphql-core/pull/59

And here is the code for each executor... you might find useful too!
https://github.com/graphql-python/graphql-core/tree/features/promises/graphql/execution/executors

**Comment by Globegitter** [comment]
Thanks, that is amazing progress @syrusakbary! Also this might be part of fixing #41 but it seems in your PR to 0.4.14 you missed: https://github.com/graphql/graphql-js/commit/3d27953a4653ca8ea5aa18edab105ca374dc0b39

**Comment by syrusakbary** [comment]
@Globegitter I skipped intentionally this as we already pass the originalError to the `GraphQLError` exception.
https://github.com/graphql-python/graphql-core/blob/master/graphql/core/execution/executor.py#L230

Maybe what is not as obvious and need to be improved is that this original error is in the `stack` attr of the `GraphQLError`.
https://github.com/graphql-python/graphql-core/blob/master/graphql/core/error.py#L15

**Comment by syrusakbary** [comment]
@sdcooke any other port of the `graphql-js` commits will be welcome! 😉

**Comment by sdcooke** [comment]
I haven't disappeared! Just not finding enough time to get to it right now. I'm currently battling against relay connections in graphene!

**Comment by syrusakbary** [comment]
All the changes are now in the `master` branch. Closing this issue :)

**Comment by Globegitter** [comment]
Wow that's amazing progress. Great job @syrusakbary! :)

**Comment by Globegitter** [comment]
Any chance to make a new realse for this @syrusakbary ?

**Comment by syrusakbary** [comment]
This new `graphql-core` version will be pushed to PyPI soon.
I'm working in updating all external dependencies (aka `graphene`, `graphql_relay`, `graphql-django-view`, `django-graphiql`, `flask-graphql`) to support the new code structure and upload a new version for them too.
