### ISSUE TITLE
Use AsyncioExecutor from within a coroutine.

### ISSUE THREAD

**Issue by saolsen** [graphql-python/graphql-core-legacy#67]
I'd like to be able to resolve a graphql query with async def resolvers from inside a coroutine.

This used to work with the old AsyncioExecutionMiddleware (I was using version 0.4.12.1) but the new AsyncExecutor seems like it's meant to be run from outside a coroutine and internally calls `loop.run_until_complete` itself but my request handler is already a coroutine so I'd like to just call
`result = await execute(...)`

**Comment by syrusakbary** [comment]
@saolsen @AlecAivazis I added the `return_promise` option to `execute` and `graphql` methods.

Now you can do:

``` python
result = await execute(schema, query_ast, return_promise=True)
```

Working test: https://github.com/graphql-python/graphql-core/blob/895b324f3810a866b2c68527a837d474c893f200/tests_py35/core_execution/test_asyncio_executor.py#L65

Hope it helps!
