### ISSUE TITLE
v0.6.1

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphql-core-legacy#75]
Not sure how much time I have the next few weeks but wanted to get the ball rolling on `v0.6.0+`. I think it is probably best to target the sub-relsease rather than straight to `0.7.0` making it easier chunks.

In any case, here is the list of commits: https://github.com/graphql/graphql-js/compare/v0.6.0...v0.6.1

As soon as I find some time I'll get started on it.

**Comment by syrusakbary** [comment]
Great! I'm taking some time to review deeply your `0.6.0` PR, but should be good to go soon! :)
