### ISSUE TITLE
"Dirty" stdout from version on pypi

### ISSUE THREAD

**Issue by temaput** [graphql-python/graphql-core-legacy#94]
Hi!
Not sure if it is the right place to report, but the latest version on pypi is not clean. It still has 
            print(field_def.args.items())
at line 36 of known_argument_names.py (and probably more alike), which brings a lot of garbage in stdout.

Latest version here does not have this issue.

**Comment by yen223** [comment]
This was fixed at https://github.com/graphql-python/graphql-core/commit/845b09b264155f82b4cba9654cec19e18bca40ab

But yeah, I'm also eagerly awaiting the next release of `graphql-core`. The print statements add a lot of noise to our unit tests, and we'd rather not have to pin the requirement to a github commit.

**Comment by syrusakbary** [comment]
Closing issue. The version `1.0.1` is now available in PyPI and should not have any print statements on it :)
